version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER : postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    image: web-template
    volumes:
      - ./project:/src
    ports:
      - 8081:8000
    command: sh -c "chmod +x entrypoint.sh && ./entrypoint.sh"
